/* Real browser integration checks. Start npm run dev, then run this file. */
const { execFileSync } = require('node:child_process');
const assert = require('node:assert/strict');
const base = process.argv[2] || 'http://localhost:8851/';
const session = 'pochadraw-smoke';
function browser(...args) { return execFileSync('npx', ['--yes','agent-browser','--session',session,...args], {encoding:'utf8',timeout:60000}).trim(); }
function evalJS(code) { return JSON.parse(browser('eval',code)); }
const click = id => evalJS(`document.querySelector(${JSON.stringify(id)}).click(); true`);
const state = () => evalJS('CC.LevelKit.read("draft", null)');
const settle = () => browser('wait','350');
function pointer(type,x,y) { evalJS(`(() => { const cv=document.querySelector('#editorCanvas'),r=cv.getBoundingClientRect();cv.dispatchEvent(new PointerEvent('${type}',{bubbles:true,clientX:r.left+${x}/16*r.width,clientY:r.top+${y}/9*r.height,pointerId:1,button:0,buttons:${type==='pointerup'?0:1}}));return true;})()`); }
try {
  browser('open',new URL('editor.html?preview=1',base).href);
  evalJS('localStorage.clear(); true');
  browser('reload');settle();
  assert.equal(evalJS('document.querySelector("#studioLibrary").hidden'),false);
  assert.equal(evalJS('document.querySelector("#editorPanel").hidden'),true);
  click('#createLevel');settle();assert.equal(state().parts.length,3);
  click('[data-toy="block"]');pointer('pointerdown',7,4);pointer('pointerup',7,4);settle();
  assert.equal(state().parts.length,4);assert.equal(state().solution.length,0);
  pointer('pointerdown',7,4);pointer('pointermove',8,5);pointer('pointerup',8,5);settle();
  assert.equal(state().parts[3].x,7.2);assert.equal(state().parts[3].y,4.4);
  click('#undoEdit');settle();assert.equal(state().parts[3].x,6.2);
  click('#redoEdit');settle();assert.equal(state().parts[3].x,7.2);
  click('.object-actions .button');settle();assert.equal(state().parts.length,5);
  click('.object-actions .danger');settle();assert.equal(state().parts.length,4);
  console.log('PASS place, select, drag, duplicate, delete, undo and redo');
  click('#tabLevels');
  assert.equal(evalJS('document.querySelectorAll(".campaign-card").length'),100);
  assert.equal(evalJS('document.querySelectorAll(".world-section").length'),10);
  assert.equal(evalJS('Array.from(document.querySelectorAll(".world-levels")).every(r=>r.children.length===10 && r.scrollWidth<=r.clientWidth && r.lastElementChild.getBoundingClientRect().top>r.firstElementChild.getBoundingClientRect().top)'),true);
  assert.equal(evalJS('!!document.querySelector("#browseWorld,header.top a")'),false);
  assert.equal(evalJS('document.querySelector(".campaign-card button").textContent'),'Remix');
  evalJS(`localStorage.setItem('campaign-original',JSON.stringify(CC.LEVELS[0])); true`);
  assert.equal(evalJS('document.querySelector("#studioPanel").hidden'),true);
  click('.campaign-card:first-child button');
  assert.equal(evalJS('document.querySelector("#tabStudio").getAttribute("aria-selected")'),'true');
  settle();assert.equal(state().custom,true);
  assert.notEqual(state().id,evalJS('CC.LEVELS[0].id'));
  console.log('PASS 100 campaign levels in 10 wrapping world grids and separate remixes');
  browser('fill','#levelName','포차 ✎ café');browser('press','Tab');settle();
  click('#saveLevel');
  assert.ok(evalJS('CC.LevelKit.read("library",[]).some(l=>l.name==="포차 ✎ café")'));
  browser('reload');settle();assert.equal(state().name,'포차 ✎ café');
  assert.equal(evalJS('document.querySelector("#editorPanel").hidden'),false);
  console.log('PASS remix, Unicode names, sketchbook save and document reload');
  click('#testLevel');
  browser('wait','--load','networkidle');
  const won=evalJS(`(() => {
    const w=document.querySelector('#playFrame').contentWindow,cv=w.document.querySelector('#cv'),r=cv.getBoundingClientRect();
    const s=w.CCDBG.st.level.solution[0],a=s.pts[0],b=s.pts[s.pts.length-1];
    const fire=(type,p)=>cv.dispatchEvent(new w.PointerEvent(type,{bubbles:true,clientX:r.left+p[0]/16*r.width,clientY:r.top+p[1]/9*r.height,pointerId:1,button:0,buttons:type==='pointerup'?0:1}));
    fire('pointerdown',a);for(let i=1;i<=50;i++)fire('pointermove',[a[0]+(b[0]-a[0])*i/50,a[1]+(b[1]-a[1])*i/50]);fire('pointerup',b);
    w.document.querySelector('#btnGo').click();w.CCDBG.advance(10);return w.CCDBG.st.sim.won;
  })()`);
  assert.equal(won,true);settle();
  assert.equal(evalJS('document.querySelector("#recordHint").hidden'),false);
  click('#recordHint');settle();assert.equal(state().hintVerified,true);
  assert.equal(evalJS('document.querySelector("#testDialog").open'),false);
  console.log('PASS pointer drawing, game physics, win message and replay-checked hint capture');
  assert.equal(evalJS('!!document.querySelector(".document-actions #testLevel")'),true);
  assert.equal(evalJS('!!document.querySelector("#selectTool svg")'),true);
  assert.equal(evalJS('!!document.querySelector(".palette-note,.stage-caption,.paper-tab,.test-strip,.bottom-actions")'),false);
  click('#saveLevel');click('#tabStudio');
  assert.equal(evalJS('document.querySelector("#studioLibrary").hidden'),false);
  assert.equal(evalJS('document.querySelector("#editorPanel").hidden'),true);
  assert.equal(evalJS(`localStorage.getItem('campaign-original')===JSON.stringify(CC.LEVELS[0])`),true);
  click('.saved-card .actions button');
  assert.equal(evalJS('document.querySelector("#editorPanel").hidden'),false);
  click('#backToStudio');
  const share=evalJS('document.querySelector(".saved-card .actions a").href');
  assert.equal(evalJS('CC.LevelKit.decode(new URL(document.querySelector(".saved-card .actions a").href).hash.slice(7)).name'),'포차 ✎ café');
  console.log('PASS compact editor controls and saved puzzle play link');
  const sharedPreview=new URL(share);sharedPreview.searchParams.set('preview','1');
  browser('open',sharedPreview.href);browser('wait','--load','networkidle');
  assert.equal(evalJS('CCDBG.st.level.name'),'포차 ✎ café');
  assert.equal(evalJS('document.querySelector("#overlay").hidden'),true);
  assert.equal(evalJS('new URL(document.querySelector("#btnLevels").href).searchParams.get("tab")'),'levels');
  assert.equal(evalJS('CCDBG.st.level.custom'),true);
  console.log('PASS shared link opens as a playable custom puzzle');
  browser('open',new URL('editor.html?preview=1',base).href);
  browser('set','viewport','390','844');settle();
  click('.saved-card .actions button');settle();
  assert.ok(evalJS('document.documentElement.scrollWidth <= innerWidth'));
  assert.ok(evalJS('document.querySelector("#editorCanvas").getBoundingClientRect().width > 250'));
  console.log('PASS mobile layout has no horizontal overflow');
  const errors=browser('errors');assert.ok(!errors,errors);
  console.log('PASS no browser errors');
} finally { browser('close'); }
